FROM daocloud.io/php:7.1.4-fpm
# Install modules
RUN apt-get update && apt-get install -y \
        libjpeg-dev libpng-dev libfreetype6-dev \
    && docker-php-ext-configure pdo_mysql  --with-pdo-mysql=mysqlnd  \
    && docker-php-ext-configure mysqli  --with-mysqli=mysqlnd \
    && docker-php-ext-configure gd -with-gd --enable-gd-native-ttf \
        --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ --with-freetype-dir=/usr/include/ \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install gd
CMD ["php-fpm"]
