#
#

version: "3"

services:
    
    web-dvwa:
        image: nginx:latest
        container_name: web-dvwa
        volumes:
            - ./conf/site.conf:/etc/nginx/conf.d/default.conf:ro
            - ./html/:/usr/share/nginx/html/
            - ./log/:/var/log/nginx/
        ports:
            - 80:80
        networks:
            - net-dvwa
        depends_on:
            - php-dvwa
            - mysql-dvwa

    php-dvwa:
        #image: php:7-fpm
        build: ./php
        container_name: php-dvwa
        volumes:
            - ./html/:/usr/share/nginx/html/
            - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
        #expose:
        #    - 9000
        networks:
            - net-dvwa
            
    mysql-dvwa:
        image: mysql:5.7
        container_name: mysql-dvwa
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - /mysql/data/:/var/lib/mysql:rw
        #expose:
        #    - 3306
        networks:
            - net-dvwa
        

networks:
    net-dvwa:
        driver: bridge
        
