#
#
# VERSION               0.0.1

FROM		ubuntu
MAINTAINER	Dragonite "weiqiangdragonite@gmail.com"

# make sure the package repository is up to date
RUN apt-get update && apt-get upgrade

# install ssh
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd

EXPOSE 22
CMD    ["/usr/sbin/sshd", "-D"]




