# VERSION 0.0.1

FROM		daocloud.io/centos:7
MAINTAINER	Dragonite "weiqiangdragonite@gmail.com"


# make sure the package repository is up to date


# install ssh
RUN yum install 
R
RUN echo 'root:screencast' | chpasswd

EXPOSE 22
CMD    ["/usr/sbin/sshd", "-D"]




